name: YouTube Fetch

on:
  #schedule:
  #  - cron: '*/5 * * * *'  # 5分ごとに実行
  workflow_dispatch:

jobs:
  fetch-and-post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies and run script
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          WP_ENDPOINT: ${{ secrets.WP_ENDPOINT }}
          WP_USER: ${{ secrets.WP_USER }}
          WP_PASS: ${{ secrets.WP_PASS }}
        run: |
          pip install requests
          python fetch_youtube.py
